export const LangDropDown = [
  {
    id: 1,
    value: 'en',
    label: 'English',
  },
  {
    id: 2,
    value: 'ar',
    label: 'عربی',
  },
  {
    id: 3,
    value: 'ur',
    label: 'اردو',
  },
];

export const themes = [
  { value: 'default', label: 'default' },
  { value: 'dark', label: 'dark' },
];

export const bookingStatuses = [
  {
    id: 1,
    value: 'newBooking',
    localizedValue: 'نئی بکنک',
  },
  {
    id: 2,
    value: 'canceled',
    localizedValue: 'کینسلڈ',
  },
  {
    id: 3,
    value: 'confirmed',
    localizedValue: 'تصدیق شدہ',
  },{
    id: 4,
    value: 'completed',
    localizedValue: 'مکمل',
  },
];

export const vehicleTypes = [
  {
    id: 1,
    value: 'Camry(4 Seater)',
    localizedValue: 'کیمرے',
  },
  {
    id: 2,
    value: 'H1 (7 Seater)',
    localizedValue: 'ایچ ون',
  },
  {
    id: 3,
    value: 'GMC(7 Seater)',
    localizedValue: 'جی ایم سی',

  },
  {
    id: 4,
    value: 'Staria(7 Seater)',
    localizedValue: 'سٹاریا',
  },
  {
    id: 5,
    value: 'Hiace(12 Seater)',
    localizedValue: 'ہائی ایس',
  },
  {
    id: 6,
    value: 'Coaster(18 Seater)',
    localizedValue: 'کوسٹر',
  },
  {
    id: 7,
    value: 'Luxury Bus(18 Seater)',
    localizedValue: 'لکثری بس',
  },
];

export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    urTitle:"ہمارے بارے",
    arTitle:"متعلق",
    links: [
      { title: "How it works", urTitle:"کیسے کام کرتا ہے", arTitle:"کیسے کام کرتا ہے", url: "/" },
      { title: "Featured", urTitle:"فیچرڈ", arTitle:"فیچرڈ", url: "/" },
      { title: "Partnership", urTitle:"سانجھا کام", arTitle:"پارٹرنرشپ", url: "/" },
      { title: "Bussiness Relation", urTitle:"کاروباری", arTitle:"تعلقات", url: "/" },
    ],
  },
  {
    title: "Company",
    urTitle:"کمپنی",
    arTitle:"کمپنی",
    links: [
      { title: "Events", urTitle:"تہوار", arTitle:"ایونٹس", url: "/" },
      { title: "Blog", urTitle:"بلاگ", arTitle:"بلاگز", url: "/" },
      { title: "Podcast", urTitle:"پوڈکاسٹ", arTitle:"پاڈکاسٹس", url: "/" },
      { title: "Invite a friend", urTitle:"دوستوں کو مدعو کریں", arTitle:"انوائٹ کریں", url: "/" },
    ],
  },
  {
    title: "Socials",
    urTitle:"سوشل",
    arTitle:"سوشل",
    links: [
      { title: "Discord", urTitle:"ختم کریں", arTitle:"ڈسکارڈ", url: "/" },
      { title: "Instagram", urTitle:"انسٹاگرام", arTitle:"انستاگرام", url: "/" },
      { title: "Twitter", urTitle:"ٹوٹر", arTitle:"توتر", url: "/" },
      { title: "Facebook", urTitle:"فیس بک", arTitle:"فیس بکس", url: "/" },
    ],
  },
];

export const allCars = [
  {
    city_mpg: 16,
    class: 'ford',
    combination_mpg: 19,
    cylinders: 6,
    displacement: 2.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 26,
    make: 'ford',
    urMake: 'فورڈ',
    arMake: 'فورڈ',
    model: 'a4',
    transmission: 'a',
    year: 1996,
    pic:'/Ford.webp'
  },
  {
    city_mpg: 17,
    class: 'Tucson',
    combination_mpg: 20,
    cylinders: 6,
    displacement: 2.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 25,
    make: 'Hyundai',
    urMake: 'ٹکسن',
    arMake: 'ٹکسن',
    model: 'TUCSON',
    transmission: 'm',
    year: 1996,
    pic:'/tucson.png'
  },
  {
    city_mpg: 16,
    class: 'compact car',
    combination_mpg: 19,
    cylinders: 6,
    displacement: 2.8,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 25,
    make: 'Hyundai',
    urMake: 'ہنڈائی',
    arMake: 'ہنڈائی',
    model: 'SONATA',
    transmission: 'a',
    year: 1996,
    pic:'/Sonata.png'
  },
  {
    city_mpg: 17,
    class: 'compact car',
    combination_mpg: 20,
    cylinders: 6,
    displacement: 2.8,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 24,
    make: 'Toyota',
    urMake: 'ٹویوٹا',
    arMake: 'ٹویوٹا',
    model: 'CAMRY',
    transmission: 'm',
    year: 1996,
    pic:'/Camry-Toyota.png'
  },
  {
    city_mpg: 18,
    class: 'compact car',
    combination_mpg: 21,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 27,
    make: 'Young-XL',
    urMake: 'ینگ ایس ایل',
    arMake: 'ینگ ایس ایل',
    model: 'GMC',
    transmission: 'a',
    year: 1997,
    pic:'/GMC-Young-XL-1.png'
  },
  {
    city_mpg: 18,
    class: 'compact car',
    combination_mpg: 21,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 27,
    make: 'Toyota',
    urMake: 'ٹویوٹا',
    arMake: 'ٹویوٹا',
    model: 'COASTER',
    transmission: 'a',
    year: 1997,
    pic:'/Coaster-Toyota.png'
  },
  {
    city_mpg: 17,
    class: 'compact car',
    combination_mpg: 20,
    cylinders: 6,
    displacement: 2.8,
    drive: 'awd',
    fuel_type: 'gas',
    highway_mpg: 24,
    make: 'Toyota',
    urMake: 'ٹویوٹا',
    arMake: 'ٹویوٹا',
    model: 'HIACE',
    transmission: 'm',
    year: 1996,
    pic:'/Hiace-Toyota-1.png'
  },
  {
    city_mpg: 18,
    class: 'compact car',
    combination_mpg: 21,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 27,
    make: 'Hyundai',
    urMake: 'ہنڈائی',
    arMake: 'ہنڈائی',
    model: 'STARIA',
    transmission: 'a',
    year: 1997,
    pic:'/Hyundai-Staria.png'
  },
  {
    city_mpg: 18,
    class: 'compact car',
    combination_mpg: 21,
    cylinders: 4,
    displacement: 1.8,
    drive: 'fwd',
    fuel_type: 'gas',
    highway_mpg: 27,
    make: 'Hyundai',
    urMake: 'ہنڈائی',
    arMake: 'ہنڈائی',
    model: 'STAREX-H1',
    transmission: 'a',
    year: 1997,
    pic:'/Hyundai-Starex-H1.png'
  },
];
